### ISSUE TITLE
Update and Upgrade

### ISSUE THREAD

**Issue by rm511130** [tybritten/pks-zsh-autocomplete-plugin#2]
Can you add the `update` and `upgrade` commands to your autocomplete plugin?
I've given it a try (and I think I'm close to getting it right), but I can't quite figure out why it's not working as expected. Here's my [code.](https://github.com/rm511130/pks-cli-oh-my-zsh-custom-plugin/blob/master/_pks)
Thank you

**Comment by tybritten** [comment]
I have it updated just didn’t push it yet. Waiting for GA to make sure there aren’t any further changes

**Comment by rm511130** [comment]
Great! Any chance you could send me an early copy? or let me know what I did wrong [here.](https://github.com/rm511130/pks-cli-oh-my-zsh-custom-plugin/blob/master/_pks)

**Comment by tybritten** [comment]
just emailed it to you

**Comment by rm511130** [comment]
Got it all to work for me, so I'm sending you a pull request.
